default:
  image: node

cache:
  paths:
    - node_modules/

stages:
  - install
  - lint
  - test
  - build

install:
  stage: install
  script:
    -  npm install

lint:
  stage: lint
  script:
    -   npm run lint

test:
  stage: test
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build